config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "users#new"

  resource :session, only: [:create, :destroy, :index]

  resources :users, except: [:destroy], shallow: true do

    resources :friendings, only: [:create, :destroy, :index], shallow: true
    resources :photos, except: [:edit, :update], shallow: true
    get "/cover-photo" => "users#edit_cover_photo"

     get "/profile-photo" => "users#edit_profile_photo"

    resources :posts, only: [:index, :create, :destroy], shallow: true do
        resources :comments, only: [:create, :destroy], shallow: true do
          resources :likes, only: [:destroy, :create], defaults: {likeable: "Comment"}

        end
        resources :likes, only: [:create], defaults: {likeable: "Post"}
        delete "/post-like" => "likes#destroy", as: :post_like, defaults: {likeable: "Post"}
    end


  end



  get "/photos" => "static_pages#photos"
  get "/edit-profile" => "static_pages#edit_profile"


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if current_user
      redirect_to timeline_path
    else
      @user = User.new
    end
  end

  def about

  end

  def timeline
    @post = Post.new
    @comment = Comment.new
  end

  def edit_profile
  end

  def friends
  end

  def photos
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_comments.html.erb
<% post.comments.each do |comment| %>
        <article class="comment posted-post row">
          <a href="timeline.html" class="my-thumbnail">
            <%= image_tag "harry_potter_small.jpg" %>
          </a>

          <a href="timeline.html"><p>Harry Potter</p></a>

    <p id="post-date"><%= post.created_at.strftime("%A %B, %d %Y") %></p>

          <p>
           <%= comment.body %>
          </p>

          <div class="row">
            <div class="col-xs-8"><a href="#" class="action" id="like">Like</a><p class="likes-count">3 other people like this</p></div>

            <div class=" col-xs-1"><a href="#" class="col-xs-1" id="delete"><p>Delete</p></a></div>
          </div>
        </article>
<% end %>

app/views/static_pages/_cover.html.erb
 <div class="row">
  <div class="cover-photo-div col-xs-12">
    <%= image_tag "hogwarts_small.jpg", class: "cover-photo" %>

    <%= image_tag "harry_potter_small.jpg", class: "profile-pic" %>

    <%= link_to  '<p class="edit-profile pull-right">Edit Profile <span class="glyphicon glyphicon-edit"></span></p>'.html_safe, edit_profile_path %>

  </div>
</div>

app/views/static_pages/_new_comment_form.html.erb
<article class="comment">
  <%= form_for @comment do |f| %>
    <%= f.text_area :body, rows: 1, placeholder: "Leave a comment...", class: "form-control" %>

      <h2>
        <div class="row">

          <!-- div class="pull-left col-xs-2 col-xs-offset-1">
            <a href="#" class="no-center" id="cancel">
              <p>Cancel</p>
            </a>
          </div> -->
         <%= f.hidden_field :commentable_id, value: post.id %>
         <%= f.hidden_field :commentable_type, value: "Post" %>
          <div class="pull-right col-xs-3">
            <%= f.submit  'Comment', class: " btn btn-primary" %>
          </div>

        </div>
      </h2>
  <% end %>
</article>

app/views/static_pages/_new_post_form.html.erb
<article>
  <h2>Post</h2>

  <%= form_for @post do |f| %>

    <%= f.text_area :body, rows: 4, placeholder: "Tell the world something...", class: "form-control" %>

    <h2><%= f.submit 'Post', class: "btn btn-primary " %></h2>
  <% end %>

</article>

app/views/static_pages/_posts.html.erb
 <% Post.all.reverse.each do |post| %>
 <article class="posted-post">
    <a href="timeline.html" class="my-thumbnail">
      <%= image_tag "harry_potter_small.jpg" %>
    </a>

    <%= link_to '<p>Harry Potter</p>'.html_safe, timeline_path %>


    <p id="post-date"><%= post.created_at.strftime("%A %B, %d %Y") %></p>


     <p><%= post.body %></p>
  <h2>
    <div class="row">
      <div class="pull-left"><a href="#" class="col-xs-1" id="like"><p>Like</p></a></div>

      <div class="pull-left"><a href="#" class="col-xs-2" id="like"><p>Comment</p></a></div>

      <div class="pull-right">
        <%= link_to '<p>Delete</p>'.html_safe, post_path(post.id), method: :delete, class: 'col-xs-1' %>
      </div>
    </div>
  </h2>

 </article>
<%= render 'comments', post: post %>

<%= render 'new_comment_form', post: post %>
 <% end %>

app/views/static_pages/_sign_up_form.html.erb
<section class="col-md-5 col-md-offset-2 col-xs-6" id="sign-up-form" >
    <h2>Sign Up</h2>

    <%= form_for @user do |f| %>

        <div class="row">
            <div class="form-group col-xs-6">
                <%= f.label :first_name, "First Name" %>
                <%= f.text_field :first_name, id: "FirstName", class: "form-control", placeholder: "First Name" %>
            </div>

            <div class="form-group col-xs-6">
                <%= f.label :last_name, "Last Name" %>
                <%= f.text_field :last_name, id: "LastName", class: "form-control", placeholder: "Last Name" %>

            </div>
        </div>


        <div class="form-group">
            <%= f.label :email, "Email" %>
            <%= f.text_field :email, id: "InputEmail", class: "form-control", placeholder: "Email" %>

        </div>

        <div class="form-group">

            <%= f.label :password, "Password" %>
            <%= f.password_field :password, id: "InputPassword", class: "form-control", placeholder: "Password" %>
        </div>

        <div class="form-group">
             <%= f.label :password_confirmation, "Confirm Password" %>
            <%= f.password_field :password_confirmation, id: "ConfirmPassword", class: "form-control", placeholder: "Confirm Password" %>
        </div>

        <div class="form-group">

            <%= f.label :birthday, "Birthday" %>
            <%= f.date_field :birthday, id: "dob", class: "form-control" %>

        </div>


        <div class="form-group">
            <%= f.label :gender, "Male", class: "radio-inline" %>

            <%= f.radio_button :gender, id: "male", value: "male" %>
            <%= f.label :gender, "Female", class: "radio-inline" %>

            <%= f.radio_button :gender, id: "female", value: "female" %>

        </div>
        <%= f.submit "Create Account", class: "btn btn-success" %>


 <% end  %>

</section>

app/views/static_pages/_subnav.html.erb
<div class="row">
   <div class=" col-xs-12 sub-nav">
    <div class="col-xs-offset-7 col-sm-offset-5 col-lg-offset-3 col-xs-6 col-sm-8 col-lg-9">
      <ul class="nav nav-pills">
        <li
          <% if params[:action] == 'timeline' %>
            class="active"
          <% end %>
        >
           <%= link_to 'Timeline', timeline_path %>
        </li>

        <li
          <% if params[:action] == 'about' %>
            class="active"
          <% end %>
          >
           <%= link_to 'About', about_path %>

        </li>

        <li
         <% if params[:action] == 'photos' %>
            class="photos"
          <% end %>
        >
          <%= link_to 'Photos <span class="badge">1310</span>'.html_safe, photos_path %>

        </li>

        <li
         <% if params[:action] == 'friends' %>
            class="friends"
          <% end %>
          >
          <%= link_to 'Friends <span class="badge">310</span>'.html_safe, friends_path %>

        </li>

    </div>
  </ul>
</div>

app/views/static_pages/about.html.erb
<%= render 'cover' %>

<%= render 'subnav' %>

<%= render 'about' %>

<%= render 'footer' %>

app/views/static_pages/edit_profile.html.erb
<%= render 'cover' %>

<%= render 'subnav' %>

 <!-- edit profile -->
  <section  class="content col-xs-12">
    <h2>Edit Profile</h2>

    <div class="row">
      <div class="col-xs-10 col-sm-4 col-sm-offset-1 col-xs-offset-1">
        <h3>Basic Information</h3>

        <form class="form-horizontal">
          <div class="form-group">
            <div class="col-xs-4"><label class="control-label">Birthday</label></div>
            <div class="col-xs-5">
              <input class="form-control" value="July 31, 1980">
            </div>
          </div>

          <div class="form-group">
            <div class="col-xs-4"><label class="control-label">College</label></div>
            <div class="col-xs-5">
              <input class="form-control" value="Hogwarts College">
            </div>
          </div>

          <div class="form-group row">
            <div class="col-xs-4"><label class="control-label">Hometown</label></div>
            <div class="col-xs-5">
              <input class="form-control" value="Godrick's Hollow, England">
            </div>
          </div>
        </form>

        <h3>Contact Information</h3>

        <form>
          <div class="form-group row">
            <div class="col-xs-3"><label class="control-label">Email</label></div>
            <div class="col-xs-6">
              <input class="form-control" value="harrypotter@hogwarts.edu">
            </div>
          </div>

          <div class="form-group row">
            <div class="col-xs-3"><label class="control-label">Telephone</label></div>
            <div class="col-xs-6">
              <input class="form-control" value="+44-555-123-4567">
            </div>
          </div>
        </form>
      </div>

      <div class="col-xs-10 col-xs-offset-1 col-sm-5 col-sm-offset-1">
        <h3>Words to Live By</h3>
        <div class="col-xs-7"><textarea class="form-control" rows="5">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat.
        </textarea></div>

        <div class="col-xs-12"><h3>About Me</h3></div>
        <div class="col-xs-7"><textarea class="form-control" rows="8">

          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat.

          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </textarea></div>
      </div>


      <div class="row">
        <div class="col-xs-2 col-xs-offset-5">
        <a href="about.html"><button class="btn btn-primary" id="submit-button">Submit</button></a>
      </div>
    </div> <!-- endrow -->
  </section>
</div> <!-- end container-fluid -->


<%= render 'footer' %>

app/views/static_pages/friends.html.erb
<%= render 'shared/cover' %>

<%= render 'shared/subnav' %>


<main class="row">
      <section class="col-xs-12 content">
        <h2>Friends</h2>

        <div class="row">
      <% 5.times do %>
          <article class="col-xs-offset-1 col-xs-10 col-lg-offset-0 col-lg-4 friend">
            <div class="row">
              <div class="col-xs-4">
                <%= image_tag "user_silhouette_generic.jpg" %>
              </div>

              <div class="col-xs-5">
                <a href="#"><p>Hermoine Granger</p></a>
                <br>
                <a href="#" id="friend-num"><p id="friend-num">400 friends</p></a>
              </div>

              <div class="col-xs-3">
                <a href="#"><button class="btn btn-success" id="unfriend">Unfriend</button>
              </div>
            </div>
          </article>

          <article class="col-xs-offset-1 col-xs-10 col-lg-offset-1 col-lg-4 friend">
            <div class="row">
              <div class="col-xs-4">
                <%= image_tag "user_silhouette_generic.jpg" %>
              </div>

              <div class="col-xs-5">
                <a href="#"><p>Hermoine Granger</p></a>
                <br>
                <a href="#" id="friend-num"><p id="friend-num">400 friends</p></a>
              </div>

              <div class="col-xs-3">
                <a href="#"><button class="btn btn-success" id="unfriend">Unfriend</button>
              </div>
            </div>
          </article>

         <% end %>
      </section>
    </main>

<%= render 'shared/footer' %>

app/views/static_pages/home.html.erb
<section class="row" id="welcome">
  <%= render 'intro_copy' %>
  <%= render 'sign_up_form' %>
</section>

<%= render 'footer' %>

app/views/static_pages/photos.html.erb
<%= render 'shared/cover' %>

<%= render 'shared/subnav' %>

<!-- photos -->
<main class="row">
  <section class="col-xs-12 content">
    <h2>Photos<a href="#"><button class="btn btn-primary btn-photo pull-right" id="add-photo">Add Photo</button></a></h2>

    <section class="row">
      <% 16.times do %>
      <article id="photo" class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <p>
          <a class="hovertext" href="#" title="Uploaded January 1, 2016">
            <%= image_tag "icon_photo_small.jpg", class: "photo" %>
          </a>
        </p>
      </article>
      <% end %>

    </section>
  </section>

</main>

<%= render 'shared/footer' %>

app/views/static_pages/timeline.html.erb
<%= render 'cover' %>

<%= render 'subnav' %>

      <!-- Timeline -->
      <section id="timeline">

        <div class="left col-xs-12 col-sm-5">

          <!-- About -->
          <article>
            <h2>About</h2>

            <form class="form-horizontal">
            <div class="form-group">
              <label class="col-xs-5 control-label">Birthday</label>
              <div class="col-xs-7">
                <p class="form-control-static">July 31, 1980</p>
              </div>
            </div>

            <div class="form-group">
              <label class="col-xs-5 control-label">College</label>
              <div class="col-xs-7">
                <p class="form-control-static">Hogwarts College</p>
              </div>
            </div>

            <div class="form-group">
              <label class="col-xs-5 control-label">Hometown</label>
                <div class="col-xs-7">
                  <p class="form-control-static">Godrick's Hollow, England</p>
                </div>
              </div>
            </form>
          </article>

          <!-- Photos -->

          <article class="photos">
            <h2>Photos (1310)</h2>

            <% 9.times do %>
              <%= image_tag "icon_photo_small.jpg", class: "photo" %>

            <% end %>


            <div class="row"><a href="photos.html">See more photos</a></div>
          </article>

            <!-- Friends -->

          <article class="friends">
            <h2>Friends (310)</h2>
            <% 9.times do %>
              <div class="friend-div">
                <%= image_tag "user_silhouette_generic.jpg", class: "friend" %>
                <p>First Last</p>
              </div>
            <% end %>


             <div class="row">
                <div class="col-xs-12">
                  <a href="friends.html">See more friends</a>
                </div>
              </div>
          </article>
        </div> <!-- end left -->


        <!-- right -->
        <div id="right" class="col-xs-12  col-sm-7">
          <!-- create post -->
          <%= render 'new_post_form' %>


        <!-- posted post -->
          <%= render 'posts' %>
        <!-- posted post with like -->
        <article class="posted-post row">
          <a href="timeline.html" class="my-thumbnail">
            <%= image_tag "harry_potter_small.jpg" %>
          </a>

          <a href="timeline.html"><p>Harry Potter</p></a>

          <p id="post-date">Posted on Thu, June 19, 2015</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>

          <h2>
            <div class="row">
              <div class="col-xs-2 col-sm-1"><a href="#" class="col-xs-1" id="like"><p>Unlike</p></a></div>

              <div class="col-xs-offset-7 col-xs-1"><a href="#" class="col-xs-1" id="delete"><p>Delete</p></a></div>
            </div>

            <div class="row">
              <p class="col-xs-12 liked-this no-center"><a href="#">Hermoine Granger</a> liked this</a></p>
            </div>
          </h2>
        </article>

        <!-- posted post you liked -->
        <article class="posted-post">
          <a href="timeline.html" class="my-thumbnail">
            <%= image_tag "harry_potter_small.jpg" %>
          </a>

          <a href="timeline.html"><p>Harry Potter</p></a>

          <p id="post-date">Posted on Thu, June 19, 2015</p>

          <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>

          <h2>
            <div class="row">
              <div class="col-xs-2 col-sm-1"><a href="#" class="col-xs-1" id="like"><p>Like</p></a></div>

              <div class="col-xs-offset-7 col-xs-1"><a href="#" class="col-xs-1" id="delete"><p>Delete</p></a></div>

            </div>

            <div class="row">
              <p class="col-xs-12 liked-this no-center">You and <a href="#">Hermoine Granger</a> liked this</a></p>
            </div>
          </h2>
        </article>

          <!-- comment -->
        <article class="comment posted-post row">
          <a href="timeline.html" class="my-thumbnail">
            <%= image_tag "ron-weasley.jpg" %>
          </a>

          <a href="timeline.html"><p>Ron Weasley</p></a>

          <p id="post-date">Posted on Thu, June 18, 2015</p>
          <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>

          <a href="#" class="action" id="like">Like</a><p class="likes-count">3 other people like this</p>

        </article>

        <!-- comment -->

        <article class="comment posted-post row">
          <a href="timeline.html" class="my-thumbnail">
            <%= image_tag "harry_potter_small.jpg" %>
          </a>

          <a href="timeline.html"><p>Harry Potter</p></a>

          <p id="post-date">Posted on Thu, June 19, 2015</p>

          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum
          </p>

          <div class="row">
            <div class="col-xs-8"><a href="#" class="action" id="like">Like</a><p class="likes-count">3 other people like this</p></div>

            <div class=" col-xs-1"><a href="#" class="col-xs-1" id="delete"><p>Delete</p></a></div>
          </div>
        </article>

<!--  -->      </div> <!-- end right -->

      </section> <!-- end timeline -->
    </div> <!-- end container fluid -->
      <!-- Footer -->

    <%= render 'footer' %>