config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "users#new"

  resource :session, only: [:create, :destroy, :index]

  resources :users, except: [:destroy], shallow: true do

    resources :friendings, only: [:create, :destroy, :index], shallow: true
    resources :photos, except: [:edit, :update], shallow: true
    get "/cover-photo" => "users#edit_cover_photo"

     get "/profile-photo" => "users#edit_profile_photo"

    resources :posts, only: [:index, :create, :destroy], shallow: true do
        resources :comments, only: [:create, :destroy], shallow: true do
          resources :likes, only: [:destroy, :create], defaults: {likeable: "Comment"}

        end
        resources :likes, only: [:create], defaults: {likeable: "Post"}
        delete "/post-like" => "likes#destroy", as: :post_like, defaults: {likeable: "Post"}
    end


  end



  get "/photos" => "static_pages#photos"
  get "/edit-profile" => "static_pages#edit_profile"


end

app/models/user.rb
class User < ApplicationRecord
  before_create :generate_auth_token
  after_create -> { create_profile }
  after_create :queue_welcome_email
  
  has_secure_password

  validates :password, length: { minimum: 6, maximum: 20 }, on: :create
  validates :first_name, presence: true, on: :create
  validates :last_name, presence: true, on: :create
  
  validates :email, 
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, 
                      on: :create }, uniqueness: true

  validates :gender, allow_nil:true, inclusion: { in: %w(male female other) }

  validates_each :birthday do |user, birthday, value|
    if value && value >= Time.now.to_date
      user.errors.add(birthday, 'must be in the past')
    end
  end

  validates_each :birthday do |user, birthday, value|
    if value && value <= (Time.now.to_date - 125.years)
      user.errors.add(birthday, 'must be less than 125 years in the past')
    end
  end

  has_many :posts
  has_many :photos
  has_many :comments
  has_one :profile, inverse_of: :user
  has_many :likes, foreign_key: "liker_id"

  # When acting as the initiator of the friending
  has_many :initiated_friendings, foreign_key: :friender_id, class_name: "Friending"
  has_many :friended_users, through: :initiated_friendings, source: :friend_recipient

  # When acting as person friended
  has_many :received_friendings, 
            foreign_key: :friended_id, 
            class_name: "Friending"

  has_many :users_friended_by, 
          through: :received_friendings, 
          source: :friend_initiator

  accepts_nested_attributes_for :profile, 
                                reject_if: :new_record?, update_only: true

  def full_name
    "#{first_name.titleize} #{last_name.titleize}"
  end

  def generate_auth_token
    begin
      self.auth_token = SecureRandom.urlsafe_base64
    end while User.exists?(auth_token: self.auth_token)
  end

  def regenerate_auth_token
    self.auth_token = nil
    generate_auth_token
    save
  end

  def queue_welcome_email
    User.delay.send_welcome_email(id)
  end

  def self.send_welcome_email(user_id)

    UserMailer.welcome(User.find(user_id)).deliver_now!

  end


  def self.search(query)
    if query
      where("first_name LIKE ? OR last_name LIKE ?", "%#{query}%", "%#{query}%")
    else
      where("")
    end
  end

  private
  def is_valid_birthday?
    if((birthday.is_a?(Date) rescue ArgumentError) == ArgumentError)
      errors.add(:birthday, 'Sorry, Invalid Date of Birth Entered.')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_login, except: [:new, :create]
  before_action :user_is_current_user?, only: [:edit, :update]

  def index
    if params[:query]
      @users = User.search(params[:query])
    else
      @users = User.all
    end
  end

  def new
    if current_user
      redirect_to user_posts_path(current_user.id)
    else
      @user = User.new
    end
  end

  def create
    if current_user
      redirect_to user_posts_path(current_user.id)
    else
      @user = User.new(user_params)

      if @user.save
        sign_in(@user)
        flash[:success] = "Congrats on making your account!"

        redirect_to user_posts_path(current_user.id)
      else
        errors = @user.errors.full_messages.join(", ")
        flash[:sorry] = "We could not create an accout. #{errors}"
        render :new
      end
    end

  end

  def show
    @profile = User.find(params[:id]).profile
  end

  def edit
    @user = User.find(params[:id])
    @profile = @user.profile
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = "You successfully updated your profile."
      redirect_to user_path(current_user.id)

    else
      errors = @user.errors.full_messages.join(", ")
      flash[:sorry] = "We could not update your profile. #{errors}"
      render :edit
    end

  end

  def edit_cover_photo
    @user = User.find(params[:user_id])
    @profile = @user.profile
    @photos = Photo.where(user_id: params[:user_id])

  end

  def edit_profile_photo
    @user = User.find(params[:user_id])
    @profile = @user.profile
    @photos = Photo.where(user_id: params[:user_id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, 
                                  :gender, :birthday, :email, :password,
                                   :password_confirmation, profile_attributes: 
                                   [:college, :city, :state, :country, :phone, 
                                    :words_to_live_by, :about_me, 
                                    :password_confirmation, :profile_photo_id, :cover_photo_id])
  end


  def user_is_current_user?
    unless params[:id].to_i == current_user.id
      flash[:error] = "Not authorized!"
      redirect_to user_posts_path(current_user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

	def get_cover_photo
		return nil unless User.find(current_page_user_id).profile.cover_photo_id
		Photo.find(User.find(current_page_user_id).profile.cover_photo_id)
	end

	def get_profile_photo
		return nil unless User.find(current_page_user_id).profile.profile_photo_id
		Photo.find(User.find(current_page_user_id).profile.profile_photo_id)
	end

end

app/views/users/_about.html.erb
<section class="content col-xs-10 col-xs-offset-1">
    <h2>About

      <% if current_page_user_id == current_user.id %>
        <%= link_to '<button class="btn btn-primary pull-right btn-edit" id="edit-button" >Edit your Profile</button>'.html_safe, edit_user_path(current_user) %>
      <% end %>
    </h2>


      <div class="row">
        <div class="col-xs-10 col-sm-4 col-sm-offset-1 col-xs-offset-1">
          <h3>Basic Information</h3>

          <div class="form-horizontal">
            <div class="form-group">
              <label class="col-xs-5 control-label">Birthday</label>
              <div class="col-xs-7">
                <p class="form-control-static">
                <% if @profile.user.birthday %>
                    <%= @profile.user.birthday.strftime("%B %d, %Y") %>
                  <% end %>
                </p>
              </div>
            </div>

            <div class="form-group">
              <label class="col-xs-5 control-label">College</label>
              <div class="col-xs-7">
                <p class="form-control-static"><%= @profile.college %></p>
              </div>
            </div>

            <div class="form-group">
              <label class="col-xs-5 control-label">Hometown</label>
              <div class="col-xs-7">
                <p class="form-control-static"><%= @profile.hometown %></p>
              </div>
            </div>
          </form>

          <h3>Contact Information</h3>

          <form>
            <div class="form-group">
              <label class="col-xs-5 control-label">Email</label>
              <div class="col-xs-7">
                <p class="form-control-static"><%= @profile.user.email %></p>
              </div>
            </div>


            <div class="form-group">
              <label class="col-xs-5 control-label">Telephone</label>
              <div class="col-xs-7">
                <p class="form-control-static"><%= @profile.phone %></p>
              </div>
            </div>

          </div>
        </div>

        <div class="col-xs-10 col-xs-offset-1 col-sm-5 col-sm-offset-1">
          <h3>Words to Live By</h3>
          <p>
            <%= @profile.words_to_live_by %>
          </p>

          <h3>About Me</h3>
          <p>
           <%= @profile.about_me %>
          </p>
        </div>


      </div>
    </div>
  </section>

app/views/users/_about_me_info.html.erb
<h3>Words to Live By</h3>
<div class="col-xs-12">

   <%= profile_fields.text_area :words_to_live_by, rows: 5, class: "form-control" %>
</div>

<div class="col-xs-12">
  <h3>About Me</h3>
</div>

<div class="col-xs-12">
  <%= profile_fields.text_area :about_me, rows: 7, class: "form-control" %>
</div>

app/views/users/_basic_info.html.erb
<div class="form-group">
  <div class="col-xs-3">
      <%= profile_fields.label :college, class: "control-label" %>
  </div>

  <div class="col-xs-8">
    <%= profile_fields.text_field :college, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="col-xs-3">
      <%= profile_fields.label :city, class: "control-label" %>
  </div>

  <div class="col-xs-4">
    <%= profile_fields.text_field :city, class: "form-control" %>
  </div>

   <div class="col-xs-1">
      <%= profile_fields.label :state, class: "control-label" %>
  </div>

  <div class="col-xs-3">
    <%= profile_fields.text_field :state, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="col-xs-3">
      <%= profile_fields.label :country, class: "control-label" %>
  </div>

  <div class="col-xs-8">
    <%= profile_fields.text_field :country, class: "form-control" %>
  </div>
</div>

app/views/users/_contact_info.html.erb
<h3>Contact Information</h3>

<div class="row">
  <div class="col-xs-3">
    <%= user_fields.label :email, class: "control-label" %>
  </div>

  <div class="col-xs-6">
    <%= user_fields.email_field :email, class: "form-control" %>
  </div>
</div>

<div class="form-group row">
  <div class="col-xs-3">
    <%= profile_fields.label :phone, "Telephone", class: "control-label" %>
  </div>

  <div class="col-xs-6">
     <%= profile_fields.telephone_field :phone, class: "form-control" %>
  </div>
</div>

app/views/users/_cover_profile_photo_form.html.erb
<div class="row">
      
  <%= form_for @user, url: { action: "update", controller: "users" , id: @user.id},  html: { class: "form-horizontal" } do |user_fields| %>

    
    <%= user_fields.fields_for :profile do |profile_fields| %> 
        <% if @photos.empty? %>
          <h3 class="text-center">You don't have any photos. Please upload some photos.</h3>
          <br>
        <% end %>
        <% @photos.each do |photo| %>

          <%=image_tag photo.file.url, class: "photo-form" %>
          <%= profile_fields.radio_button fk, photo.id %>
        <% end %>
    <% end %>

    <div class="row">
      <div class="col-xs-2 col-xs-offset-5">
      <% unless @photos.empty? %>

        <%= user_fields.submit class: "btn btn-primary" %>
      <% end %>
      </div>
    <% end %>
    </div>
</div>

app/views/users/_intro_copy.html.erb
<section class="col-md-5 col-xs-6" id="intro-copy">

    <h3>Connect with all your friends!</h3>
    <br>
    <ul>
        <li>See photos and updates in your news feed.</li>

        <li>Post your status for the world to see from your profile</li>

        <li>Get in touch with your friends by "friending" them.</li>

        <li>Like things because you're a positive person!</li>

    </ul>
</section>

app/views/users/_sign_up_form.html.erb
<section class="col-md-5 col-md-offset-2 col-xs-6" id="sign-up-form" >
    <h2>Sign Up</h2>

    <%= form_for @user do |f| %>

        <div class="row">
            <div class="form-group col-xs-6">
                <%= f.label :first_name, "First Name" %>
                <%= f.text_field :first_name, id: "FirstName", class: "form-control", placeholder: "First Name" %>
            </div>

            <div class="form-group col-xs-6">
                <%= f.label :last_name, "Last Name" %>
                <%= f.text_field :last_name, id: "LastName", class: "form-control", placeholder: "Last Name" %>

            </div>
        </div>


        <div class="form-group">
            <%= f.label :email, "Email" %>
            <%= f.text_field :email, id: "InputEmail", class: "form-control", placeholder: "Email" %>

        </div>

        <div class="form-group">

            <%= f.label :password, "Password" %>
            <%= f.password_field :password, id: "InputPassword", class: "form-control", placeholder: "Password" %>
        </div>

        <div class="form-group">
            <%= f.password_field :password_confirmation, id: "ConfirmPassword", class: "form-control", placeholder: "Confirm Password" %>
        </div>

        <div class="form-group">

            <%= f.label :birthday, "Birthday" %>
            <%= f.date_field :birthday, id: "dob", class: "form-control" %>

        </div>


        <div class="form-group">
            <%= f.label :gender, "Male", class: "radio-inline", id: "male" %>

            <%= f.radio_button :gender, "male" %>
            <%= f.label :gender, "Female", class: "radio-inline", id: "female" %>

            <%= f.radio_button :gender, "female"  %>

            <%= f.label :gender, "Other", class: "radio-inline", id: "other" %>
            <%= f.radio_button :gender, "other"  %>

        </div>
        <%= f.submit "Create Account", class: "btn btn-success" %>


 <% end  %>

</section>

app/views/users/edit.html.erb
<%= render 'shared/cover' %>

<%= render 'shared/subnav' %>



  <section  class="content col-xs-10 col-xs-offset-1">
    <h2>Edit Profile</h2>

    <div class="row">
    <div class="col-xs-offset-4">
      <%= link_to "Edit Cover Photo", user_cover_photo_path(current_user.id), class: "btn btn-primary " %>
      <%= link_to "Edit Profile Picture", user_profile_photo_path(current_user.id), class: "btn btn-warning " %>
    </div>
    </div>
      <%= form_for @user, url: { action: "update", controller: "users" },  html: { class: "form-horizontal" } do |user_fields| %>

        <div class="col-xs-12 col-sm-5 col-sm-offset-1 col-xs-offset-1">
          <h3>Basic Information</h3>

          <div class="form-group">
            <div class="col-xs-3">

              <%= user_fields.label :birthday, class: "control-label" %>
            </div>

            <div class="col-xs-8">
              <%= user_fields.date_field :birthday, class: "form-control" %>
            </div>
          </div>
          <%= user_fields.fields_for :profile do |profile_fields| %>
            <%= render 'basic_info', profile_fields: profile_fields %>
            <%= render 'contact_info', profile_fields: profile_fields, user_fields: user_fields %>

          </div>

          <div class="col-xs-10  col-sm-5 ">
            <%= render 'about_me_info', profile_fields: profile_fields %>
          </div>

          <% end %>
        <div class="row">

          <div class="col-xs-2 col-xs-offset-5">
            <%= user_fields.submit class: "btn btn-success" %>
          </div>

        </div>
      </div>
    <% end %>
  </section>


<%= render 'shared/footer' %>

app/views/users/edit_cover_photo.html.erb
<%= render 'shared/cover' %>

<%= render 'shared/subnav' %>

  <section  class="content col-xs-12">
    <h2>Edit Cover Photo</h2>

    <div class="row">

      
      <%= form_for @user, url: { action: "update", controller: "users" , id: @user.id},  html: { class: "form-horizontal" } do |user_fields| %>

    
          <%= user_fields.fields_for :profile do |profile_fields| %>
             
            <% @photos.each do |photo| %>
              <%=image_tag photo.file.url %>

              <%= profile_fields.radio_button :cover_photo_id, photo.id %>
            <% end %>
         <% end %>

        <div class="row">

          <div class="col-xs-2 col-xs-offset-5">
            <%= user_fields.submit class: "btn btn-primary" %>
                    <% end %>
</div>

        </div>
      </div>
  </section>


<%= render 'shared/footer' %>

app/views/users/edit_profile_photo.html.erb
<%= render 'shared/cover' %>

<%= render 'shared/subnav' %>

  <section  class="content col-xs-12">
    <h2>Edit Cover Photo</h2>

    <%= render 'cover_profile_photo_form.html.erb', fk: :profile_photo_id %>
      
  </section>


<%= render 'shared/footer' %>

app/views/users/index.html.erb
<div class="all-users">
  <h1 class="text-center">Users</h1>
<% @users.each_with_index do |user, i| %>
  <article class="col-xs-offset-1 col-xs-10

    <% if i.even? %>
      col-lg-offset-1
    <% else %>
      col-lg-offset-0
    <% end %>
      col-lg-5 friend">

    <div class="row">
      <div class="col-xs-4">
      <% if user.profile.profile_photo %>
        <%= image_tag user.profile.profile_photo.file.url, class: "friend" %>
      <% else %>
        <%= image_tag "default_profile_photo.jpg", class: "friend" %>

      <% end %>
    
      </div>

      <div class="friend-info col-xs-5">
        
        <%= link_to user.full_name, user_posts_path(user_id: user.id), id: "friend_name" %>
        <br>
        <% friend_count = Friending.where(friender_id: user.id).count %>
        <p id="friend-num"><%= link_to friend_count, user_friendings_path(user_id: user.id), id: "friend-num" %> Friends</p>
      </div>

      <div class="col-xs-3">
        
        <% if Friending.where(friender_id: current_user.id, friended_id: user.id).first %>
            <%= link_to '<button class="btn btn-danger" id="unfriend">Unfriend</button>'.html_safe, friending_path(user.id), method: :delete %>
          <% else %>
            <%= link_to '<button class="btn btn-success" id="unfriend">Friend</button>'.html_safe, user_friendings_path(user.id), method: :post  %>
          <% end %>

        
      </div>
    </div>
  </article>

<% end %>
</div>
</div>
<%= render "shared/footer" %>
 

app/views/users/new.html.erb
<section class="row" id="welcome">
  <%= render 'intro_copy' %>
  <%= render 'sign_up_form' %>
</section>

<%= render 'shared/footer' %>

app/views/users/show.html.erb
<%= render 'shared/cover' %>

<%= render 'shared/subnav' %>

<%= render 'about' %>

<%= render 'shared/footer' %>