config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "users#new"

  resource :session, only: [:create, :destroy, :index]

  resources :users, except: [:destroy], shallow: true do

    resources :friendings, only: [:create, :destroy, :index], shallow: true
    resources :photos, except: [:edit, :update], shallow: true
    get "/cover-photo" => "users#edit_cover_photo"

     get "/profile-photo" => "users#edit_profile_photo"

    resources :posts, only: [:index, :create, :destroy], shallow: true do
        resources :comments, only: [:create, :destroy], shallow: true do
          resources :likes, only: [:destroy, :create], defaults: {likeable: "Comment"}

        end
        resources :likes, only: [:create], defaults: {likeable: "Post"}
        delete "/post-like" => "likes#destroy", as: :post_like, defaults: {likeable: "Post"}
    end


  end



  get "/photos" => "static_pages#photos"
  get "/edit-profile" => "static_pages#edit_profile"


end

app/views/shared/_cover.html.erb
 <div class="row">
  <div class="cover-photo-div col-xs-10 col-xs-offset-1">
    <% if get_cover_photo %>
       <%= image_tag get_cover_photo.file.url, class: "cover-photo" %>
    <% else %>
      <%= image_tag "default_cover_photo.jpg", class: "cover-photo" %>
    <% end %>


    <% if get_profile_photo %>
        <%= image_tag get_profile_photo.file.url, class: "profile-pic" %>
    <% else %>
        <%= image_tag "default_profile_photo.jpg", class: "profile-pic" %>
    <% end %>
 

    

    <h1 id="cover-name"><%= User.find(current_page_user_id).full_name %></h1>
      <% if current_page_user_id == current_user.id %>
        <%= link_to  '<p class="edit-profile pull-right">Edit Profile <span class="glyphicon glyphicon-edit"></span></p>'.html_safe, edit_user_path(current_user) %>
      <% elsif !current_user.friended_users.include?(User.find(current_page_user_id)) %>
       <%= link_to  '<p class="edit-profile pull-right">Add Friend<span class="glyphicon glyphicon-edit"></span></p>'.html_safe, user_friendings_path(current_page_user_id), method: :post %>
      <% end %>
  </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>

    <% if type == "sorry" || type == "error" %>
      <div class="alert alert-danger" id="error-flash">
        <strong><%= type.capitalize %>! <%= message %></strong>
      </div>

    <% else %>
      <div class="alert alert-success", id="success-flash">
        <strong><%= type.capitalize %>! <%= message %></strong>
      </div>

    <% end %>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<hr>
<footer class="footer">
    <p>© 2016 HBook, Inc.</p>
</footer>
<br>

app/views/shared/_subnav.html.erb
<% if params[:user_id] %>
  <% user_id = params[:user_id] %>
<% else %>
   <% user_id = params[:id] %>
<% end %>

<div class="row">
   <div class=" col-xs-10 col-xs-offset-1 sub-nav">
    <div class="col-xs-offset-7 col-sm-offset-5 col-lg-offset-3 col-xs-6 col-sm-8 col-lg-9">
      <ul class="nav nav-pills">
        <li
          <% if params[:action] == 'index' && params[:controller] == "posts" %>
            class="active"
          <% end %>
        >
           <%= link_to 'Timeline', user_posts_path(current_page_user_id) %>
        </li>

        <li
          <% if params[:action] == 'show' && params[:controller] == 'users' %>
            class="active"
          <% end %>
          >
           <%= link_to 'About', user_path(current_page_user_id) %>

        </li>

        <li
         <% if params[:controller] == 'photos' %>
              class="active"
          <% end %>
          >
        <%= link_to "Photos <span class='badge'>#{User.find(current_page_user_id).photos.count}</span>".html_safe, user_photos_path(current_page_user_id) %>

        </li>

        <li
         <% if  params[:controller] == 'friendings' %>
               class="active"
          <% end %>
          >
          <%= link_to "Friends <span class='badge'>#{User.find(current_page_user_id).friended_users.count}</span>".html_safe, user_friendings_path(current_page_user_id) %>

        </li>

    </div>
  </ul>
</div>