config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "users#new"

  resource :session, only: [:create, :destroy, :index]

  resources :users, except: [:destroy], shallow: true do

    resources :friendings, only: [:create, :destroy, :index], shallow: true
    resources :photos, except: [:edit, :update], shallow: true
    get "/cover-photo" => "users#edit_cover_photo"

     get "/profile-photo" => "users#edit_profile_photo"

    resources :posts, only: [:index, :create, :destroy], shallow: true do
        resources :comments, only: [:create, :destroy], shallow: true do
          resources :likes, only: [:destroy, :create], defaults: {likeable: "Comment"}

        end
        resources :likes, only: [:create], defaults: {likeable: "Post"}
        delete "/post-like" => "likes#destroy", as: :post_like, defaults: {likeable: "Post"}
    end


  end



  get "/photos" => "static_pages#photos"
  get "/edit-profile" => "static_pages#edit_profile"


end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id'

  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :comments, as: :commentable, dependent: :destroy

  has_many :likes, as: :likeable
  validates :body, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login

  def index
    @user = User.find(params[:user_id])
    @profile = @user.profile
    @post = Post.new
    @empty_comment = Comment.new
    @posts = Post.where(receiver_id: @user.id).all.reverse
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.receiver_id = params[:user_id]

    if @post.save
      # @user = User.find(params[:user_id])
      # @profile = @user.profile
      @empty_comment = Comment.new

      flash[:success] = "Thank you for your post."

      respond_to do |format|
        format.html { redirect_to user_posts_path(params[:user_id]) }
        format.js
      end
    else


      errors = @post.errors.full_messages.join(", ")
      flash[:error] = "could not post #{errors}"
      redirect_to user_posts_path(params[:user_id])
    end
  end

  def destroy
    user_id = Post.find(params[:id]).user_id
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to referer }
      format.js
    end
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  def other_likes(likeable)

    likes = likeable.likes
    likers = likes.map { |like| like.liker }
    return if likes.length < 1
    if likes.length == 1
      if likers.first == current_user
        "You liked this"
      else
        "#{likes.first.liker.full_name} liked this"
      end

    elsif likes.length == 2
      if likers.any? { |u| u == current_user }
        likers.delete(current_user)
        "You and #{likers.first.full_name} liked this"
      else
        "#{likers.first.full_name} and #{likers.second.full_name} liked this"
      end

    else
      "#{likers.first.full_name} and #{likers.second.full_name} and #{likes.count - 2} others liked this"

    end
  end


  def current_page_user_id


    if params[:user_id]
        return params[:user_id].to_i
    elsif params[:controller] ==  "photos" && params[:action] == "show"
      return Photo.find(params[:id]).user_id
    else
      return params[:id].to_i
    end
  end

end

app/views/posts/_comment_like.html.erb
    <div class="likesection">

      <div class="pull-left" id="comment-like-div">

      <% unless comment.likes.any? { |like| like.liker == current_user } %>
        <%= link_to "<p>Like</p>".html_safe, comment_likes_path(comment.id), method: :post, class: "likes-count", remote: true %>

        <% else %>
          <%= link_to "<p>Unlike</p>".html_safe, like_path(comment.id), method: :delete, class: "likes-count", remote: true %>
      <% end %>
        <p class="liked-this"><%= other_likes(comment) %></p>

      </div>
      </div>

app/views/posts/_comments.html.erb
<% post.comments.each do |comment| %>
  <%= render "posts/comment", comment: comment, post: post %>
<% end %>

app/views/posts/_like.html.erb
      <div class="pull-left" id="comment-like-div">

      <% unless comment.likes.any? { |like| like.liker == current_user } %>
        <%= link_to "<p>Like</p>".html_safe, comment_likes_path(comment.id), method: :post, class: "likes-count", remote: true %>

        <% else %>
          <%= link_to "<p>Unlike</p>".html_safe, like_path(comment.id), method: :delete, class: "likes-count", remote: true %>
      <% end %>
        <p class="liked-this"><%= other_likes(comment) %></p>

      </div>

app/views/posts/_new_post_form.html.erb
<article>
  <h2>Post</h2>

  <%= form_for [:user, @post], remote: true do |f| %>

    <%= f.text_area :body, rows: 4, placeholder: "Tell the world something...", class: "form-control", id: "new-post" %>

    <h2><%= f.submit 'Post', class: "btn btn-primary " %></h2>
  <% end %>

</article>

app/views/posts/_post.html.erb
<div data-post-id="<%= post.id %>">
  <div class="post-and-comments">
    <article class="posted-post">
        <a href="timeline.html" class="my-thumbnail">
          <% if post.author.profile.profile_photo %>
            <%= image_tag post.author.profile.profile_photo.file.url, class: "friend" %>
          <% else %>
            <%= image_tag "default_profile_photo.jpg", class: "friend" %>

          <% end %>
        </a>

        <%= link_to post.author.full_name, user_posts_path(current_user.id), id: "post-name" %>


        <p id="post-date"><%= post.created_at.strftime("%A %B %d, %Y") %></p>


         <p><%= post.body %></p>
      <h2>
        <div class="row">



        <%= render "post_like", post: post %>



        <% if post.author == current_user %>

          <div class="pull-right">
            <%= link_to '<p>Delete</p>'.html_safe, post_path(id: post.id), method: :delete, class: 'col-xs-1', id: "delete-post", remote: true %>
          </div>
        <% end %>
        </div>
      </h2>

     </article>
    <%= render 'posts/comments', post: post %>
    </div>
    <%= render 'posts/new_comment_form', post: post, empty_comment: @empty_comment %>
</div>

app/views/posts/_post_like.html.erb
  <div class="pull-left likesection">
  <% unless post.likes.any? { |like| like.liker == current_user } %>
    <%= link_to "<p>Like</p>".html_safe, post_likes_path(post.id), method: :post, remote: true %>

    <% else %>
      <%= link_to "<p>Unlike</p>".html_safe, post_post_like_path(post.id), method: :delete, remote: true %>
  <% end %>
    <p class="liked-this"><%= other_likes(post) %></p>

  </div>

app/views/posts/_posts.html.erb
<% Post.where(receiver_id: user.id).all.reverse.each do |post| %>
 <%= render post %>
<% end %>

app/views/posts/_timeline_about.html.erb
<article>
  <h2>About</h2>

  <form class="form-horizontal">
  <div class="form-group">
    <label class="col-xs-5 control-label">Birthday</label>
    <div class="col-xs-7">
      <p class="form-control-static">
    <% if profile.user.birthday %>
        <%= profile.user.birthday.strftime("%B %d, %Y")  %>
      <% end %>
      </p>
    </div>
  </div>

  <div class="form-group">
    <label class="col-xs-5 control-label">College</label>
    <div class="col-xs-7">
      <p class="form-control-static"><%= profile.college %></p>
    </div>
  </div>

    <div class="form-group">
      <label class="col-xs-5 control-label">Hometown</label>
        <div class="col-xs-7">
          <p class="form-control-static"><%= profile.hometown %></p>
        </div>
    </div>
  </form>
</article>

app/views/posts/_timeline_friends.html.erb
 <article class="friends">
  <h2>Friends (<%= User.find(current_page_user_id).friended_users.count %>)</h2>
  <% @user.friended_users.limit(9).each do |friend| %>
    <div class="friend-div">

      <% if friend.profile.profile_photo %>
        <%= image_tag friend.profile.profile_photo.file.url(:thumb), class: "friend" %>
      <% else %>
        <%= image_tag "default_profile_photo.jpg", class: "friend" %>

      <% end %>
      <p><%= friend.full_name %></p>
    </div>
  <% end %>


   <div class="row">
      <div class="col-xs-12">
        <%= link_to "See more friends", user_friendings_path(params[:user_id]) %>
      </div>
    </div>
</article>

app/views/posts/create.js.erb
$newPost = "<%= j(render @post) %>"
$posts = $(".posts")

$posts.prepend($newPost)

app/views/posts/destroy.js.erb
(function() {
  var $postDiv = $('div[data-post-id="<%= @post.id %>"]');
  $postDiv.remove();
})();

app/views/posts/destroy_comment.js.erb
(function() {
  var $comment = $('article[data-comment-id="<%= @comment.id %>"]');
  $comment.remove();
})();

app/views/posts/index.html.erb
<%= render 'shared/cover' %>
<%= render 'shared/subnav' %>

<section id="timeline">
  <div class="left col-xs-12 col-sm-4 col-sm-offset-1">
    <%= render 'timeline_about', profile: @profile %>
    <%= render 'timeline_photos' %>
    <%= render 'timeline_friends' %>
  </div> <!-- end left -->



  <div id="right" class="col-xs-12  col-sm-6">

    <%= render 'new_post_form' %>

    <div class="posts">
      <%= render @posts %>
    </div>

  </div>
  </div>
</section>
<%= render 'shared/footer' %>

app/views/posts/new_comment.js.erb
(function() {
  var newComment = "<%= j(render 'posts/comment', comment: @comment, post: @post) %>"
  var $newComment = $(newComment)
  var $postDiv = $('div[data-post-id="<%= @post.id %>"]').children().filter(".post-and-comments");
  $newComment.appendTo($postDiv).hide().slideDown();
})();